"""Repo hygiene the reviewer should not have to remember.

Two rules, both mechanical. Em dashes are banned outright. Tool attribution is
banned because authorship of this repository is not a build artifact.

Scans tracked files only, so vendored and generated trees stay out of scope.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

EM_DASH = "—"

# Product prose discusses AI-generated documents constantly; that is the problem
# domain. Only attribution of authorship is banned, so the patterns are specific.
_TOOLS = ("claude", "copilot", "chatgpt", "codex", r"cursor\.sh")
_PHRASES = ("generated by ai", "written by ai", "ai[- ]assisted")
ATTRIBUTION = re.compile(r"(?i)\b(" + "|".join((*_TOOLS, *_PHRASES)) + r")\b")

SCANNED_SUFFIXES = frozenset(
    {".py", ".md", ".toml", ".yaml", ".yml", ".json", ".txt", ".ts", ".tsx", ".js", ".jsx", ".css"}
)
# This file necessarily contains every pattern it searches for.
SKIP = ("LICENSE", "uv.lock", "web/package-lock.json", "scripts/check_prose.py")


def tracked_files() -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
    return [Path(p) for p in out if Path(p).suffix in SCANNED_SUFFIXES and p not in SKIP]


def scan(path: Path) -> list[str]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return []
    problems = []
    for number, line in enumerate(lines, start=1):
        if EM_DASH in line:
            problems.append(f"{path}:{number}: em dash")
        if match := ATTRIBUTION.search(line):
            problems.append(f"{path}:{number}: tool attribution ({match.group(0)})")
    return problems


def main() -> int:
    problems = [problem for path in tracked_files() for problem in scan(path)]
    if not problems:
        return 0
    print("\n".join(problems), file=sys.stderr)
    print(f"\n{len(problems)} prose issue(s).", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
